name: roulette_wheel_and_sus
description: Roullete Wheel and SUS are two method for Selection of Survivor on Fitness proportion   
version: 1.0.0
homepage: https://github.com/moein-keyvani-pur/roulette_wheel_and_sus/blob/main/README.md

repository: https://github.com/moein-keyvani-pur/roulette_wheel_and_sus.git

environment:
  sdk: '>=2.12.0 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
